version: "3.9"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "todoApp"
      POSTGRES_USER: "todoApp"
      POSTGRES_PASSWORD: "MEGA_UNREAL_SECRET_PASSWORD"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U habrpguser -d habrdb" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
